## Site / lab specific configuration.

[site]
abbreviation = 'UOBC' # 4-letter abbreviation, no digits, to be used in the BIDS subject identifiers
long = 'University of Birmingham, Cruse lab' # longer format to identify lab

[monitor]
width = 60.00 # width of the screen in centimeters (without the frame)
distance = 60 # distance of the participants eyes to the screen in centimeters
resolution = [1920, 1080] # width, height pixels of the monitor 
refresh_rate = 120 # refresh rate (as reported by OS or from hardware specs)

[triggers]
type = 'labjack' # serial, parallel, labjack or viewpixx
address = '' # hardware address of the trigger port (not all types require this)
baudrate = 0 # speed of the trigger port (only applies to serial port)